/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/
 
//var bGround = require('fcc-express-bground');
//var myApp = require('./myApp');
var express = require('express');
var app = express();

// Logs all request paths and method
// app.use(function (req, res, next) {
//   res.set('x-timestamp', Date.now())
//   res.set('x-powered-by', 'freecodecamp.com')
//   console.log(`[${new Date().toISOString()}] ${req.ip} ${req.method} ${req.path}`);
//   next();
// });

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

// var options = {
//   dotfiles: 'ignore',
//   etag: false,
//   extensions: ['htm', 'html','css','js','ico','jpg','jpeg','png','svg'],
//   index: ['index.html'],
//   maxAge: '1m',
//   redirect: false
// };

app.use('/public', express.static(process.cwd() + '/public'));

app.get('/',(req,res)=>{
  res.sendFile(__dirname + "/views/index.html");
});

app.get('/json',(req,res)=>{
  res.json({"message": "Hello json"});
});

var port = process.env.PORT || 3000;
// bGround.setupBackgroundApp(app, myApp, __dirname).listen(port, function(){
//   bGround.log('Node is listening on port '+ port + '...')
// });
const listener = app.listen(port, function () {
  console.log("Node.js listening on port " + listener.address().port);
});

/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

